using MetaDslx.CodeAnalysis;
using MetaDslx.CodeAnalysis.Syntax.InternalSyntax;

#nullable enable

namespace MetaDslx.Bootstrap.MetaCompiler.Compiler.Syntax
{
	public enum CompilerSyntaxKind
	{
		__FirstToken = TComma,
		__LastToken = TInvalidToken,
		__FirstFixedToken = TComma,
		__LastFixedToken = TPlusQuestion,
		__FirstRule = Main,
		__LastRule = ArrayExpressionBlock1Block1,

		// Built-in:
		None = InternalSyntaxKind.None,
		List = InternalSyntaxKind.List,
		BadToken = InternalSyntaxKind.BadToken,
		MissingToken = InternalSyntaxKind.MissingToken,
		SkippedTokensTrivia = InternalSyntaxKind.SkippedTokensTrivia,
		DisabledTextTrivia = InternalSyntaxKind.DisabledTextTrivia,
		ConflictMarkerTrivia = InternalSyntaxKind.ConflictMarkerTrivia,
		Eof = InternalSyntaxKind.Eof,

		// Tokens:
		TComma,
		Utf8Bom,
		KNamespace,
		TSemicolon,
		KUsing,
		KLanguage,
		KReturns,
		TColon,
		TBar,
		KBlock,
		TLParen,
		TRParen,
		KAlt,
		TEqGt,
		THash,
		THashLBrace,
		TRBrace,
		KEof,
		KToken,
		KHidden,
		KFragment,
		TTilde,
		TDot,
		TDotDot,
		KNull,
		KTrue,
		KFalse,
		TLBrace,
		TLBracket,
		TRBracket,
		TEq,
		TQuestionEq,
		TExclEq,
		TPlusEq,
		TQuestion,
		TAsterisk,
		TPlus,
		TQuestionQuestion,
		TAsteriskQuestion,
		TPlusQuestion,
		TInteger,
		TDecimal,
		TPrimitiveType,
		TIdentifier,
		TVerbatimIdentifier,
		TString,
		DoubleQuoteTextCharacter,
		DoubleQuoteTextSimple,
		SingleQuoteTextCharacter,
		SingleQuoteTextSimple,
		CharacterEscapeSimple,
		CharacterEscapeSimpleCharacter,
		CharacterEscapeUnicode,
		HexDigit,
		TWhitespace,
		TLineEnd,
		TSingleLineComment,
		TMultiLineComment,
		TInvalidToken,

		// Rules:
		Main,
		Using,
		Declarations,
		LanguageDeclaration,
		Grammar,
		GrammarRuleAlt1,
		Block,
		Token,
		Fragment,
		Rule,
		Alternative,
		Element,
		BlockInline,
		Eof1,
		Keyword,
		RuleRefAlt1,
		RuleRefAlt2,
		RuleRefAlt3,
		LAlternative,
		LElement,
		LBlock,
		LFixed,
		LWildCard,
		LRange,
		LReference,
		ExpressionAlt1,
		ArrayExpression,
		SingleExpression,
		ParserAnnotation,
		LexerAnnotation,
		AnnotationArguments,
		AnnotationArgument,
		ReturnTypeIdentifierAlt1,
		ReturnTypeIdentifierAlt2,
		ReturnTypeQualifierAlt1,
		ReturnTypeQualifierAlt2,
		Name,
		Qualifier,
		QualifierList,
		IdentifierAlt1,
		IdentifierAlt2,
		SimpleQualifier,
		SimpleIdentifier,
		GrammarBlock1,
		RuleBlock1Alt1,
		RuleBlock1Alt2,
		RuleBlock2,
		BlockBlock1,
		BlockBlock2,
		BlockInlineBlock1,
		AlternativeBlock1,
		AlternativeBlock2,
		ElementBlock1,
		RuleRefAlt3Block1,
		TokenBlock1Alt1,
		TokenBlock1Alt2,
		TokenBlock2,
		FragmentBlock1,
		LBlockBlock1,
		SingleExpressionBlock1Alt4,
		SingleExpressionBlock1Alt5,
		SingleExpressionBlock1Alt6,
		SingleExpressionBlock1Tokens,
		ArrayExpressionBlock1,
		AnnotationArgumentsBlock1,
		AnnotationArgumentBlock1,
		QualifierBlock1,
		QualifierListBlock1,
		SimpleQualifierBlock1,
		AlternativeBlock1Block1,
		TokenBlock1Alt1Block1,
		ArrayExpressionBlock1Block1,
	}

    public static class CompilerSyntaxKindExtensions
    {
        public static CompilerSyntaxKind GetCompilerKind(this SyntaxToken token)
        {
            return (CompilerSyntaxKind)token.RawKind;
        }
    }
}
