//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MetaParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MetaDslx.Languages.MetaModel.Compiler {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MetaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface IMetaParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_Main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_Main([NotNull] MetaParser.Pr_MainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_Using"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_Using([NotNull] MetaParser.Pr_UsingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_Declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_Declarations([NotNull] MetaParser.Pr_DeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_MetaModel</c>
	/// labeled alternative in <see cref="MetaParser.pr_MetaDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaModel([NotNull] MetaParser.Pr_MetaModelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_MetaConstant</c>
	/// labeled alternative in <see cref="MetaParser.pr_MetaDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaConstant([NotNull] MetaParser.Pr_MetaConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_MetaEnumType</c>
	/// labeled alternative in <see cref="MetaParser.pr_MetaDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaEnumType([NotNull] MetaParser.Pr_MetaEnumTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_MetaClass</c>
	/// labeled alternative in <see cref="MetaParser.pr_MetaDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaClass([NotNull] MetaParser.Pr_MetaClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_EnumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_EnumBody([NotNull] MetaParser.Pr_EnumBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_EnumLiterals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_EnumLiterals([NotNull] MetaParser.Pr_EnumLiteralsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_MetaEnumLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaEnumLiteral([NotNull] MetaParser.Pr_MetaEnumLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_ClassNameAlt1</c>
	/// labeled alternative in <see cref="MetaParser.pr_ClassName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_ClassNameAlt1([NotNull] MetaParser.Pr_ClassNameAlt1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_ClassNameAlt2</c>
	/// labeled alternative in <see cref="MetaParser.pr_ClassName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_ClassNameAlt2([NotNull] MetaParser.Pr_ClassNameAlt2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_BaseClasses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_BaseClasses([NotNull] MetaParser.Pr_BaseClassesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_ClassBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_ClassBody([NotNull] MetaParser.Pr_ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_MetaProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaProperty([NotNull] MetaParser.Pr_MetaPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_PropertyNameAlt1</c>
	/// labeled alternative in <see cref="MetaParser.pr_PropertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_PropertyNameAlt1([NotNull] MetaParser.Pr_PropertyNameAlt1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_PropertyNameAlt2</c>
	/// labeled alternative in <see cref="MetaParser.pr_PropertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_PropertyNameAlt2([NotNull] MetaParser.Pr_PropertyNameAlt2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_PropertyOpposite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_PropertyOpposite([NotNull] MetaParser.Pr_PropertyOppositeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_PropertySubsets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_PropertySubsets([NotNull] MetaParser.Pr_PropertySubsetsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_PropertyRedefines"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_PropertyRedefines([NotNull] MetaParser.Pr_PropertyRedefinesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_MetaOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaOperation([NotNull] MetaParser.Pr_MetaOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_ParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_ParameterList([NotNull] MetaParser.Pr_ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_MetaParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaParameter([NotNull] MetaParser.Pr_MetaParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_TypeReferenceTokens</c>
	/// labeled alternative in <see cref="MetaParser.pr_TypeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_TypeReferenceTokens([NotNull] MetaParser.Pr_TypeReferenceTokensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_MetaArrayType</c>
	/// labeled alternative in <see cref="MetaParser.pr_TypeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaArrayType([NotNull] MetaParser.Pr_MetaArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_TypeReferenceAlt3</c>
	/// labeled alternative in <see cref="MetaParser.pr_TypeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_TypeReferenceAlt3([NotNull] MetaParser.Pr_TypeReferenceAlt3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_Name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_Name([NotNull] MetaParser.Pr_NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_Qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_Qualifier([NotNull] MetaParser.Pr_QualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_QualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_QualifierList([NotNull] MetaParser.Pr_QualifierListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_Identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_Identifier([NotNull] MetaParser.Pr_IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_EnumLiteralsBlock1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_EnumLiteralsBlock1([NotNull] MetaParser.Pr_EnumLiteralsBlock1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_BaseClassesBlock1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_BaseClassesBlock1([NotNull] MetaParser.Pr_BaseClassesBlock1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_MetaPropertyBlock2Alt1</c>
	/// labeled alternative in <see cref="MetaParser.pr_MetaPropertyBlock2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaPropertyBlock2Alt1([NotNull] MetaParser.Pr_MetaPropertyBlock2Alt1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_MetaPropertyBlock2Alt2</c>
	/// labeled alternative in <see cref="MetaParser.pr_MetaPropertyBlock2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaPropertyBlock2Alt2([NotNull] MetaParser.Pr_MetaPropertyBlock2Alt2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pr_MetaPropertyBlock2Alt3</c>
	/// labeled alternative in <see cref="MetaParser.pr_MetaPropertyBlock2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_MetaPropertyBlock2Alt3([NotNull] MetaParser.Pr_MetaPropertyBlock2Alt3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_PropertyOppositeBlock1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_PropertyOppositeBlock1([NotNull] MetaParser.Pr_PropertyOppositeBlock1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_PropertySubsetsBlock1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_PropertySubsetsBlock1([NotNull] MetaParser.Pr_PropertySubsetsBlock1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_PropertyRedefinesBlock1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_PropertyRedefinesBlock1([NotNull] MetaParser.Pr_PropertyRedefinesBlock1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_ParameterListBlock1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_ParameterListBlock1([NotNull] MetaParser.Pr_ParameterListBlock1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_QualifierBlock1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_QualifierBlock1([NotNull] MetaParser.Pr_QualifierBlock1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MetaParser.pr_QualifierListBlock1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPr_QualifierListBlock1([NotNull] MetaParser.Pr_QualifierListBlock1Context context);
}
} // namespace MetaDslx.Languages.MetaModel.Compiler
