//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MetaParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MetaDslx.Languages.MetaModel.Compiler {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public partial class MetaParser : global::MetaDslx.Languages.MetaCompiler.Antlr.AntlrParser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LR_TComma=1, LR_KNamespace=2, LR_TSemicolon=3, LR_KUsing=4, LR_KMetamodel=5, 
		LR_KConst=6, LR_KEnum=7, LR_TLBrace=8, LR_TRBrace=9, LR_KAbstract=10, 
		LR_KClass=11, LR_TDollar=12, LR_TColon=13, LR_KContains=14, LR_KDerived=15, 
		LR_KOpposite=16, LR_TLParen=17, LR_TRParen=18, LR_KBool=19, LR_KInt=20, 
		LR_KString=21, LR_KType=22, LR_KVoid=23, LR_TLBracket=24, LR_TRBracket=25, 
		LR_TDot=26, LR_TInteger=27, LR_TDecimal=28, LR_TIdentifier=29, LR_TString=30, 
		LR_TWhitespace=31, LR_TLineEnd=32, LR_TSingleLineComment=33, LR_TMultiLineComment=34;
	public const int
		RULE_pr_Main = 0, RULE_pr_Using = 1, RULE_pr_Declarations = 2, RULE_pr_MetaDeclaration = 3, 
		RULE_pr_EnumBody = 4, RULE_pr_EnumLiterals = 5, RULE_pr_MetaEnumLiteral = 6, 
		RULE_pr_ClassName = 7, RULE_pr_BaseClasses = 8, RULE_pr_ClassBody = 9, 
		RULE_pr_MetaProperty = 10, RULE_pr_PropertyName = 11, RULE_pr_PropertyOpposite = 12, 
		RULE_pr_MetaOperation = 13, RULE_pr_ParameterList = 14, RULE_pr_MetaParameter = 15, 
		RULE_pr_TypeReference = 16, RULE_pr_Name = 17, RULE_pr_Qualifier = 18, 
		RULE_pr_QualifierList = 19, RULE_pr_Identifier = 20, RULE_pr_EnumLiteralsBlock1 = 21, 
		RULE_pr_BaseClassesBlock1 = 22, RULE_pr_ParameterListBlock1 = 23, RULE_pr_QualifierBlock1 = 24, 
		RULE_pr_QualifierListBlock1 = 25;
	public static readonly string[] ruleNames = {
		"pr_Main", "pr_Using", "pr_Declarations", "pr_MetaDeclaration", "pr_EnumBody", 
		"pr_EnumLiterals", "pr_MetaEnumLiteral", "pr_ClassName", "pr_BaseClasses", 
		"pr_ClassBody", "pr_MetaProperty", "pr_PropertyName", "pr_PropertyOpposite", 
		"pr_MetaOperation", "pr_ParameterList", "pr_MetaParameter", "pr_TypeReference", 
		"pr_Name", "pr_Qualifier", "pr_QualifierList", "pr_Identifier", "pr_EnumLiteralsBlock1", 
		"pr_BaseClassesBlock1", "pr_ParameterListBlock1", "pr_QualifierBlock1", 
		"pr_QualifierListBlock1"
	};

	private static readonly string[] _LiteralNames = {
		null, "','", "'namespace'", "';'", "'using'", "'metamodel'", "'const'", 
		"'enum'", "'{'", "'}'", "'abstract'", "'class'", "'$'", "':'", "'contains'", 
		"'derived'", "'opposite'", "'('", "')'", "'bool'", "'int'", "'string'", 
		"'type'", "'void'", "'['", "']'", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LR_TComma", "LR_KNamespace", "LR_TSemicolon", "LR_KUsing", "LR_KMetamodel", 
		"LR_KConst", "LR_KEnum", "LR_TLBrace", "LR_TRBrace", "LR_KAbstract", "LR_KClass", 
		"LR_TDollar", "LR_TColon", "LR_KContains", "LR_KDerived", "LR_KOpposite", 
		"LR_TLParen", "LR_TRParen", "LR_KBool", "LR_KInt", "LR_KString", "LR_KType", 
		"LR_KVoid", "LR_TLBracket", "LR_TRBracket", "LR_TDot", "LR_TInteger", 
		"LR_TDecimal", "LR_TIdentifier", "LR_TString", "LR_TWhitespace", "LR_TLineEnd", 
		"LR_TSingleLineComment", "LR_TMultiLineComment"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MetaParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static MetaParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MetaParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MetaParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Pr_MainContext : ParserRuleContext {
		public IToken kNamespace;
		public Pr_QualifierContext nameAntlr1;
		public IToken tSemicolon;
		public Pr_UsingContext _pr_Using;
		public IList<Pr_UsingContext> _usingAntlr1 = new List<Pr_UsingContext>();
		public Pr_DeclarationsContext declarationsAntlr1;
		public IToken eof;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KNamespace() { return GetToken(MetaParser.LR_KNamespace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TSemicolon() { return GetToken(MetaParser.LR_TSemicolon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_DeclarationsContext pr_Declarations() {
			return GetRuleContext<Pr_DeclarationsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(MetaParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_UsingContext[] pr_Using() {
			return GetRuleContexts<Pr_UsingContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_UsingContext pr_Using(int i) {
			return GetRuleContext<Pr_UsingContext>(i);
		}
		public Pr_MainContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Main; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Main(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MainContext pr_Main() {
		Pr_MainContext _localctx = new Pr_MainContext(Context, State);
		EnterRule(_localctx, 0, RULE_pr_Main);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52;
			_localctx.kNamespace = Match(LR_KNamespace);
			State = 53;
			_localctx.nameAntlr1 = pr_Qualifier();
			State = 54;
			_localctx.tSemicolon = Match(LR_TSemicolon);
			State = 58;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==LR_KUsing) {
				{
				{
				State = 55;
				_localctx._pr_Using = pr_Using();
				_localctx._usingAntlr1.Add(_localctx._pr_Using);
				}
				}
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 61;
			_localctx.declarationsAntlr1 = pr_Declarations();
			State = 62;
			_localctx.eof = Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_UsingContext : ParserRuleContext {
		public IToken kUsing;
		public Pr_QualifierContext namespacesAntlr1;
		public IToken tSemicolon;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KUsing() { return GetToken(MetaParser.LR_KUsing, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TSemicolon() { return GetToken(MetaParser.LR_TSemicolon, 0); }
		public Pr_UsingContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Using; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Using(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_UsingContext pr_Using() {
		Pr_UsingContext _localctx = new Pr_UsingContext(Context, State);
		EnterRule(_localctx, 2, RULE_pr_Using);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			_localctx.kUsing = Match(LR_KUsing);
			State = 65;
			_localctx.namespacesAntlr1 = pr_Qualifier();
			State = 66;
			_localctx.tSemicolon = Match(LR_TSemicolon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_DeclarationsContext : ParserRuleContext {
		public Pr_MetaDeclarationContext _pr_MetaDeclaration;
		public IList<Pr_MetaDeclarationContext> _declarationsAntlr1 = new List<Pr_MetaDeclarationContext>();
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaDeclarationContext[] pr_MetaDeclaration() {
			return GetRuleContexts<Pr_MetaDeclarationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaDeclarationContext pr_MetaDeclaration(int i) {
			return GetRuleContext<Pr_MetaDeclarationContext>(i);
		}
		public Pr_DeclarationsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Declarations; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Declarations(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_DeclarationsContext pr_Declarations() {
		Pr_DeclarationsContext _localctx = new Pr_DeclarationsContext(Context, State);
		EnterRule(_localctx, 4, RULE_pr_Declarations);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 3296L) != 0)) {
				{
				{
				State = 68;
				_localctx._pr_MetaDeclaration = pr_MetaDeclaration();
				_localctx._declarationsAntlr1.Add(_localctx._pr_MetaDeclaration);
				}
				}
				State = 73;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_MetaDeclarationContext : ParserRuleContext {
		public Pr_MetaDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_MetaDeclaration; } }
	 
		public Pr_MetaDeclarationContext() { }
		public virtual void CopyFrom(Pr_MetaDeclarationContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Pr_MetaEnumTypeContext : Pr_MetaDeclarationContext {
		public IToken kEnum;
		public Pr_NameContext nameAntlr1;
		public Pr_EnumBodyContext enumBodyAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KEnum() { return GetToken(MetaParser.LR_KEnum, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_EnumBodyContext pr_EnumBody() {
			return GetRuleContext<Pr_EnumBodyContext>(0);
		}
		public Pr_MetaEnumTypeContext(Pr_MetaDeclarationContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaEnumType(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_MetaModelContext : Pr_MetaDeclarationContext {
		public IToken kMetamodel;
		public Pr_NameContext nameAntlr1;
		public IToken tSemicolon;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KMetamodel() { return GetToken(MetaParser.LR_KMetamodel, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TSemicolon() { return GetToken(MetaParser.LR_TSemicolon, 0); }
		public Pr_MetaModelContext(Pr_MetaDeclarationContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaModel(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_MetaConstantContext : Pr_MetaDeclarationContext {
		public IToken kConst;
		public Pr_TypeReferenceContext typeAntlr1;
		public Pr_NameContext nameAntlr1;
		public IToken tSemicolon;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KConst() { return GetToken(MetaParser.LR_KConst, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_TypeReferenceContext pr_TypeReference() {
			return GetRuleContext<Pr_TypeReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TSemicolon() { return GetToken(MetaParser.LR_TSemicolon, 0); }
		public Pr_MetaConstantContext(Pr_MetaDeclarationContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaConstant(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_MetaClassContext : Pr_MetaDeclarationContext {
		public IToken isAbstract;
		public IToken kClass;
		public Pr_ClassNameContext nameAntlr1;
		public Pr_BaseClassesContext baseClassesAntlr1;
		public Pr_ClassBodyContext classBodyAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KClass() { return GetToken(MetaParser.LR_KClass, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_ClassNameContext pr_ClassName() {
			return GetRuleContext<Pr_ClassNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_ClassBodyContext pr_ClassBody() {
			return GetRuleContext<Pr_ClassBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KAbstract() { return GetToken(MetaParser.LR_KAbstract, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_BaseClassesContext pr_BaseClasses() {
			return GetRuleContext<Pr_BaseClassesContext>(0);
		}
		public Pr_MetaClassContext(Pr_MetaDeclarationContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaClass(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MetaDeclarationContext pr_MetaDeclaration() {
		Pr_MetaDeclarationContext _localctx = new Pr_MetaDeclarationContext(Context, State);
		EnterRule(_localctx, 6, RULE_pr_MetaDeclaration);
		int _la;
		try {
			State = 97;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LR_KMetamodel:
				_localctx = new Pr_MetaModelContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 74;
				((Pr_MetaModelContext)_localctx).kMetamodel = Match(LR_KMetamodel);
				State = 75;
				((Pr_MetaModelContext)_localctx).nameAntlr1 = pr_Name();
				State = 76;
				((Pr_MetaModelContext)_localctx).tSemicolon = Match(LR_TSemicolon);
				}
				break;
			case LR_KConst:
				_localctx = new Pr_MetaConstantContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 78;
				((Pr_MetaConstantContext)_localctx).kConst = Match(LR_KConst);
				State = 79;
				((Pr_MetaConstantContext)_localctx).typeAntlr1 = pr_TypeReference(0);
				State = 80;
				((Pr_MetaConstantContext)_localctx).nameAntlr1 = pr_Name();
				State = 81;
				((Pr_MetaConstantContext)_localctx).tSemicolon = Match(LR_TSemicolon);
				}
				break;
			case LR_KEnum:
				_localctx = new Pr_MetaEnumTypeContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 83;
				((Pr_MetaEnumTypeContext)_localctx).kEnum = Match(LR_KEnum);
				State = 84;
				((Pr_MetaEnumTypeContext)_localctx).nameAntlr1 = pr_Name();
				State = 85;
				((Pr_MetaEnumTypeContext)_localctx).enumBodyAntlr1 = pr_EnumBody();
				}
				break;
			case LR_KAbstract:
			case LR_KClass:
				_localctx = new Pr_MetaClassContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 88;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LR_KAbstract) {
					{
					State = 87;
					((Pr_MetaClassContext)_localctx).isAbstract = Match(LR_KAbstract);
					}
				}

				State = 90;
				((Pr_MetaClassContext)_localctx).kClass = Match(LR_KClass);
				State = 91;
				((Pr_MetaClassContext)_localctx).nameAntlr1 = pr_ClassName();
				State = 93;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LR_TColon) {
					{
					State = 92;
					((Pr_MetaClassContext)_localctx).baseClassesAntlr1 = pr_BaseClasses();
					}
				}

				State = 95;
				((Pr_MetaClassContext)_localctx).classBodyAntlr1 = pr_ClassBody();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_EnumBodyContext : ParserRuleContext {
		public IToken tLBrace;
		public Pr_EnumLiteralsContext enumLiteralsAntlr1;
		public IToken tRBrace;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TLBrace() { return GetToken(MetaParser.LR_TLBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TRBrace() { return GetToken(MetaParser.LR_TRBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_EnumLiteralsContext pr_EnumLiterals() {
			return GetRuleContext<Pr_EnumLiteralsContext>(0);
		}
		public Pr_EnumBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_EnumBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_EnumBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_EnumBodyContext pr_EnumBody() {
		Pr_EnumBodyContext _localctx = new Pr_EnumBodyContext(Context, State);
		EnterRule(_localctx, 8, RULE_pr_EnumBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99;
			_localctx.tLBrace = Match(LR_TLBrace);
			State = 101;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LR_TIdentifier) {
				{
				State = 100;
				_localctx.enumLiteralsAntlr1 = pr_EnumLiterals();
				}
			}

			State = 103;
			_localctx.tRBrace = Match(LR_TRBrace);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_EnumLiteralsContext : ParserRuleContext {
		public Pr_MetaEnumLiteralContext literalsAntlr1;
		public Pr_EnumLiteralsBlock1Context _pr_EnumLiteralsBlock1;
		public IList<Pr_EnumLiteralsBlock1Context> _enumLiteralsBlock1Antlr1 = new List<Pr_EnumLiteralsBlock1Context>();
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaEnumLiteralContext pr_MetaEnumLiteral() {
			return GetRuleContext<Pr_MetaEnumLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_EnumLiteralsBlock1Context[] pr_EnumLiteralsBlock1() {
			return GetRuleContexts<Pr_EnumLiteralsBlock1Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_EnumLiteralsBlock1Context pr_EnumLiteralsBlock1(int i) {
			return GetRuleContext<Pr_EnumLiteralsBlock1Context>(i);
		}
		public Pr_EnumLiteralsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_EnumLiterals; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_EnumLiterals(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_EnumLiteralsContext pr_EnumLiterals() {
		Pr_EnumLiteralsContext _localctx = new Pr_EnumLiteralsContext(Context, State);
		EnterRule(_localctx, 10, RULE_pr_EnumLiterals);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			_localctx.literalsAntlr1 = pr_MetaEnumLiteral();
			State = 109;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==LR_TComma) {
				{
				{
				State = 106;
				_localctx._pr_EnumLiteralsBlock1 = pr_EnumLiteralsBlock1();
				_localctx._enumLiteralsBlock1Antlr1.Add(_localctx._pr_EnumLiteralsBlock1);
				}
				}
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_MetaEnumLiteralContext : ParserRuleContext {
		public Pr_NameContext nameAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		public Pr_MetaEnumLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_MetaEnumLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaEnumLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MetaEnumLiteralContext pr_MetaEnumLiteral() {
		Pr_MetaEnumLiteralContext _localctx = new Pr_MetaEnumLiteralContext(Context, State);
		EnterRule(_localctx, 12, RULE_pr_MetaEnumLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 112;
			_localctx.nameAntlr1 = pr_Name();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_ClassNameContext : ParserRuleContext {
		public Pr_ClassNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_ClassName; } }
	 
		public Pr_ClassNameContext() { }
		public virtual void CopyFrom(Pr_ClassNameContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Pr_ClassNameAlt1Context : Pr_ClassNameContext {
		public IToken tIdentifierAntlr1;
		public IToken tDollar;
		public Pr_IdentifierContext symbolTypeAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TDollar() { return GetToken(MetaParser.LR_TDollar, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_IdentifierContext pr_Identifier() {
			return GetRuleContext<Pr_IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TIdentifier() { return GetToken(MetaParser.LR_TIdentifier, 0); }
		public Pr_ClassNameAlt1Context(Pr_ClassNameContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_ClassNameAlt1(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_ClassNameAlt2Context : Pr_ClassNameContext {
		public IToken tIdentifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TIdentifier() { return GetToken(MetaParser.LR_TIdentifier, 0); }
		public Pr_ClassNameAlt2Context(Pr_ClassNameContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_ClassNameAlt2(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_ClassNameContext pr_ClassName() {
		Pr_ClassNameContext _localctx = new Pr_ClassNameContext(Context, State);
		EnterRule(_localctx, 14, RULE_pr_ClassName);
		int _la;
		try {
			State = 120;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				_localctx = new Pr_ClassNameAlt1Context(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 115;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LR_TIdentifier) {
					{
					State = 114;
					((Pr_ClassNameAlt1Context)_localctx).tIdentifierAntlr1 = Match(LR_TIdentifier);
					}
				}

				State = 117;
				((Pr_ClassNameAlt1Context)_localctx).tDollar = Match(LR_TDollar);
				State = 118;
				((Pr_ClassNameAlt1Context)_localctx).symbolTypeAntlr1 = pr_Identifier();
				}
				break;
			case 2:
				_localctx = new Pr_ClassNameAlt2Context(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 119;
				((Pr_ClassNameAlt2Context)_localctx).tIdentifierAntlr1 = Match(LR_TIdentifier);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_BaseClassesContext : ParserRuleContext {
		public Pr_BaseClassesBlock1Context baseClassesBlock1Antlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_BaseClassesBlock1Context pr_BaseClassesBlock1() {
			return GetRuleContext<Pr_BaseClassesBlock1Context>(0);
		}
		public Pr_BaseClassesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_BaseClasses; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_BaseClasses(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_BaseClassesContext pr_BaseClasses() {
		Pr_BaseClassesContext _localctx = new Pr_BaseClassesContext(Context, State);
		EnterRule(_localctx, 16, RULE_pr_BaseClasses);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 122;
			_localctx.baseClassesBlock1Antlr1 = pr_BaseClassesBlock1();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_ClassBodyContext : ParserRuleContext {
		public IToken tLBrace;
		public Pr_MetaPropertyContext _pr_MetaProperty;
		public IList<Pr_MetaPropertyContext> _propertiesAntlr1 = new List<Pr_MetaPropertyContext>();
		public IToken tRBrace;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TLBrace() { return GetToken(MetaParser.LR_TLBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TRBrace() { return GetToken(MetaParser.LR_TRBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaPropertyContext[] pr_MetaProperty() {
			return GetRuleContexts<Pr_MetaPropertyContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaPropertyContext pr_MetaProperty(int i) {
			return GetRuleContext<Pr_MetaPropertyContext>(i);
		}
		public Pr_ClassBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_ClassBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_ClassBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_ClassBodyContext pr_ClassBody() {
		Pr_ClassBodyContext _localctx = new Pr_ClassBodyContext(Context, State);
		EnterRule(_localctx, 18, RULE_pr_ClassBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			_localctx.tLBrace = Match(LR_TLBrace);
			State = 128;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 553172992L) != 0)) {
				{
				{
				State = 125;
				_localctx._pr_MetaProperty = pr_MetaProperty();
				_localctx._propertiesAntlr1.Add(_localctx._pr_MetaProperty);
				}
				}
				State = 130;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 131;
			_localctx.tRBrace = Match(LR_TRBrace);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_MetaPropertyContext : ParserRuleContext {
		public IToken isContainment;
		public IToken isDerived;
		public Pr_TypeReferenceContext typeAntlr1;
		public Pr_PropertyNameContext nameAntlr1;
		public Pr_PropertyOppositeContext propertyOppositeAntlr1;
		public IToken tSemicolon;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_TypeReferenceContext pr_TypeReference() {
			return GetRuleContext<Pr_TypeReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_PropertyNameContext pr_PropertyName() {
			return GetRuleContext<Pr_PropertyNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TSemicolon() { return GetToken(MetaParser.LR_TSemicolon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KContains() { return GetToken(MetaParser.LR_KContains, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KDerived() { return GetToken(MetaParser.LR_KDerived, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_PropertyOppositeContext pr_PropertyOpposite() {
			return GetRuleContext<Pr_PropertyOppositeContext>(0);
		}
		public Pr_MetaPropertyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_MetaProperty; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaProperty(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MetaPropertyContext pr_MetaProperty() {
		Pr_MetaPropertyContext _localctx = new Pr_MetaPropertyContext(Context, State);
		EnterRule(_localctx, 20, RULE_pr_MetaProperty);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LR_KContains:
				{
				State = 133;
				_localctx.isContainment = Match(LR_KContains);
				}
				break;
			case LR_KDerived:
				{
				State = 134;
				_localctx.isDerived = Match(LR_KDerived);
				}
				break;
			case LR_KBool:
			case LR_KInt:
			case LR_KString:
			case LR_KType:
			case LR_KVoid:
			case LR_TIdentifier:
				break;
			default:
				break;
			}
			State = 137;
			_localctx.typeAntlr1 = pr_TypeReference(0);
			State = 138;
			_localctx.nameAntlr1 = pr_PropertyName();
			State = 140;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LR_KOpposite) {
				{
				State = 139;
				_localctx.propertyOppositeAntlr1 = pr_PropertyOpposite();
				}
			}

			State = 142;
			_localctx.tSemicolon = Match(LR_TSemicolon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_PropertyNameContext : ParserRuleContext {
		public Pr_PropertyNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_PropertyName; } }
	 
		public Pr_PropertyNameContext() { }
		public virtual void CopyFrom(Pr_PropertyNameContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Pr_PropertyNameAlt2Context : Pr_PropertyNameContext {
		public IToken tIdentifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TIdentifier() { return GetToken(MetaParser.LR_TIdentifier, 0); }
		public Pr_PropertyNameAlt2Context(Pr_PropertyNameContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_PropertyNameAlt2(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_PropertyNameAlt1Context : Pr_PropertyNameContext {
		public IToken tIdentifierAntlr1;
		public IToken tDollar;
		public IToken symbolPropertyAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TDollar() { return GetToken(MetaParser.LR_TDollar, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LR_TIdentifier() { return GetTokens(MetaParser.LR_TIdentifier); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TIdentifier(int i) {
			return GetToken(MetaParser.LR_TIdentifier, i);
		}
		public Pr_PropertyNameAlt1Context(Pr_PropertyNameContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_PropertyNameAlt1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_PropertyNameContext pr_PropertyName() {
		Pr_PropertyNameContext _localctx = new Pr_PropertyNameContext(Context, State);
		EnterRule(_localctx, 22, RULE_pr_PropertyName);
		int _la;
		try {
			State = 150;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				_localctx = new Pr_PropertyNameAlt1Context(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 145;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LR_TIdentifier) {
					{
					State = 144;
					((Pr_PropertyNameAlt1Context)_localctx).tIdentifierAntlr1 = Match(LR_TIdentifier);
					}
				}

				State = 147;
				((Pr_PropertyNameAlt1Context)_localctx).tDollar = Match(LR_TDollar);
				State = 148;
				((Pr_PropertyNameAlt1Context)_localctx).symbolPropertyAntlr1 = Match(LR_TIdentifier);
				}
				break;
			case 2:
				_localctx = new Pr_PropertyNameAlt2Context(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 149;
				((Pr_PropertyNameAlt2Context)_localctx).tIdentifierAntlr1 = Match(LR_TIdentifier);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_PropertyOppositeContext : ParserRuleContext {
		public IToken kOpposite;
		public Pr_QualifierContext OppositeAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KOpposite() { return GetToken(MetaParser.LR_KOpposite, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		public Pr_PropertyOppositeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_PropertyOpposite; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_PropertyOpposite(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_PropertyOppositeContext pr_PropertyOpposite() {
		Pr_PropertyOppositeContext _localctx = new Pr_PropertyOppositeContext(Context, State);
		EnterRule(_localctx, 24, RULE_pr_PropertyOpposite);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152;
			_localctx.kOpposite = Match(LR_KOpposite);
			State = 153;
			_localctx.OppositeAntlr1 = pr_Qualifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_MetaOperationContext : ParserRuleContext {
		public Pr_TypeReferenceContext returnTypeAntlr1;
		public Pr_NameContext nameAntlr1;
		public IToken tLParen;
		public Pr_ParameterListContext parameterListAntlr1;
		public IToken tRParen;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_TypeReferenceContext pr_TypeReference() {
			return GetRuleContext<Pr_TypeReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TLParen() { return GetToken(MetaParser.LR_TLParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TRParen() { return GetToken(MetaParser.LR_TRParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_ParameterListContext pr_ParameterList() {
			return GetRuleContext<Pr_ParameterListContext>(0);
		}
		public Pr_MetaOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_MetaOperation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MetaOperationContext pr_MetaOperation() {
		Pr_MetaOperationContext _localctx = new Pr_MetaOperationContext(Context, State);
		EnterRule(_localctx, 26, RULE_pr_MetaOperation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 155;
			_localctx.returnTypeAntlr1 = pr_TypeReference(0);
			State = 156;
			_localctx.nameAntlr1 = pr_Name();
			State = 157;
			_localctx.tLParen = Match(LR_TLParen);
			State = 159;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 553123840L) != 0)) {
				{
				State = 158;
				_localctx.parameterListAntlr1 = pr_ParameterList();
				}
			}

			State = 161;
			_localctx.tRParen = Match(LR_TRParen);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_ParameterListContext : ParserRuleContext {
		public Pr_MetaParameterContext parametersAntlr1;
		public Pr_ParameterListBlock1Context _pr_ParameterListBlock1;
		public IList<Pr_ParameterListBlock1Context> _parameterListBlock1Antlr1 = new List<Pr_ParameterListBlock1Context>();
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaParameterContext pr_MetaParameter() {
			return GetRuleContext<Pr_MetaParameterContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_ParameterListBlock1Context[] pr_ParameterListBlock1() {
			return GetRuleContexts<Pr_ParameterListBlock1Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_ParameterListBlock1Context pr_ParameterListBlock1(int i) {
			return GetRuleContext<Pr_ParameterListBlock1Context>(i);
		}
		public Pr_ParameterListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_ParameterList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_ParameterList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_ParameterListContext pr_ParameterList() {
		Pr_ParameterListContext _localctx = new Pr_ParameterListContext(Context, State);
		EnterRule(_localctx, 28, RULE_pr_ParameterList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 163;
			_localctx.parametersAntlr1 = pr_MetaParameter();
			State = 167;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==LR_TComma) {
				{
				{
				State = 164;
				_localctx._pr_ParameterListBlock1 = pr_ParameterListBlock1();
				_localctx._parameterListBlock1Antlr1.Add(_localctx._pr_ParameterListBlock1);
				}
				}
				State = 169;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_MetaParameterContext : ParserRuleContext {
		public Pr_TypeReferenceContext typeAntlr1;
		public Pr_NameContext nameAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_TypeReferenceContext pr_TypeReference() {
			return GetRuleContext<Pr_TypeReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		public Pr_MetaParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_MetaParameter; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaParameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MetaParameterContext pr_MetaParameter() {
		Pr_MetaParameterContext _localctx = new Pr_MetaParameterContext(Context, State);
		EnterRule(_localctx, 30, RULE_pr_MetaParameter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 170;
			_localctx.typeAntlr1 = pr_TypeReference(0);
			State = 171;
			_localctx.nameAntlr1 = pr_Name();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_TypeReferenceContext : ParserRuleContext {
		public Pr_TypeReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_TypeReference; } }
	 
		public Pr_TypeReferenceContext() { }
		public virtual void CopyFrom(Pr_TypeReferenceContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Pr_TypeReferenceTokensContext : Pr_TypeReferenceContext {
		public IToken kBool;
		public IToken kInt;
		public IToken kString;
		public IToken kType;
		public IToken kVoid;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KBool() { return GetToken(MetaParser.LR_KBool, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KInt() { return GetToken(MetaParser.LR_KInt, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KString() { return GetToken(MetaParser.LR_KString, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KType() { return GetToken(MetaParser.LR_KType, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KVoid() { return GetToken(MetaParser.LR_KVoid, 0); }
		public Pr_TypeReferenceTokensContext(Pr_TypeReferenceContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_TypeReferenceTokens(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_MetaArrayTypeContext : Pr_TypeReferenceContext {
		public Pr_TypeReferenceContext itemTypeAntlr1;
		public IToken tLBracket;
		public IToken tRBracket;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_TypeReferenceContext pr_TypeReference() {
			return GetRuleContext<Pr_TypeReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TLBracket() { return GetToken(MetaParser.LR_TLBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TRBracket() { return GetToken(MetaParser.LR_TRBracket, 0); }
		public Pr_MetaArrayTypeContext(Pr_TypeReferenceContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaArrayType(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_TypeReferenceAlt3Context : Pr_TypeReferenceContext {
		public Pr_QualifierContext qualifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		public Pr_TypeReferenceAlt3Context(Pr_TypeReferenceContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_TypeReferenceAlt3(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_TypeReferenceContext pr_TypeReference() {
		return pr_TypeReference(0);
	}

	private Pr_TypeReferenceContext pr_TypeReference(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		Pr_TypeReferenceContext _localctx = new Pr_TypeReferenceContext(Context, _parentState);
		Pr_TypeReferenceContext _prevctx = _localctx;
		int _startState = 32;
		EnterRecursionRule(_localctx, 32, RULE_pr_TypeReference, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 182;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LR_TIdentifier:
				{
				_localctx = new Pr_TypeReferenceAlt3Context(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 174;
				((Pr_TypeReferenceAlt3Context)_localctx).qualifierAntlr1 = pr_Qualifier();
				}
				break;
			case LR_KBool:
			case LR_KInt:
			case LR_KString:
			case LR_KType:
			case LR_KVoid:
				{
				_localctx = new Pr_TypeReferenceTokensContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 180;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case LR_KBool:
					{
					State = 175;
					((Pr_TypeReferenceTokensContext)_localctx).kBool = Match(LR_KBool);
					}
					break;
				case LR_KInt:
					{
					State = 176;
					((Pr_TypeReferenceTokensContext)_localctx).kInt = Match(LR_KInt);
					}
					break;
				case LR_KString:
					{
					State = 177;
					((Pr_TypeReferenceTokensContext)_localctx).kString = Match(LR_KString);
					}
					break;
				case LR_KType:
					{
					State = 178;
					((Pr_TypeReferenceTokensContext)_localctx).kType = Match(LR_KType);
					}
					break;
				case LR_KVoid:
					{
					State = 179;
					((Pr_TypeReferenceTokensContext)_localctx).kVoid = Match(LR_KVoid);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 189;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new Pr_MetaArrayTypeContext(new Pr_TypeReferenceContext(_parentctx, _parentState));
					((Pr_MetaArrayTypeContext)_localctx).itemTypeAntlr1 = _prevctx;
					PushNewRecursionContext(_localctx, _startState, RULE_pr_TypeReference);
					State = 184;
					if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
					State = 185;
					((Pr_MetaArrayTypeContext)_localctx).tLBracket = Match(LR_TLBracket);
					State = 186;
					((Pr_MetaArrayTypeContext)_localctx).tRBracket = Match(LR_TRBracket);
					}
					} 
				}
				State = 191;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Pr_NameContext : ParserRuleContext {
		public Pr_IdentifierContext identifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_IdentifierContext pr_Identifier() {
			return GetRuleContext<Pr_IdentifierContext>(0);
		}
		public Pr_NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_NameContext pr_Name() {
		Pr_NameContext _localctx = new Pr_NameContext(Context, State);
		EnterRule(_localctx, 34, RULE_pr_Name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192;
			_localctx.identifierAntlr1 = pr_Identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_QualifierContext : ParserRuleContext {
		public Pr_IdentifierContext identifierAntlr1;
		public Pr_QualifierBlock1Context _pr_QualifierBlock1;
		public IList<Pr_QualifierBlock1Context> _qualifierBlock1Antlr1 = new List<Pr_QualifierBlock1Context>();
		[System.Diagnostics.DebuggerNonUserCode] public Pr_IdentifierContext pr_Identifier() {
			return GetRuleContext<Pr_IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierBlock1Context[] pr_QualifierBlock1() {
			return GetRuleContexts<Pr_QualifierBlock1Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierBlock1Context pr_QualifierBlock1(int i) {
			return GetRuleContext<Pr_QualifierBlock1Context>(i);
		}
		public Pr_QualifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Qualifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Qualifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_QualifierContext pr_Qualifier() {
		Pr_QualifierContext _localctx = new Pr_QualifierContext(Context, State);
		EnterRule(_localctx, 36, RULE_pr_Qualifier);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 194;
			_localctx.identifierAntlr1 = pr_Identifier();
			State = 198;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 195;
					_localctx._pr_QualifierBlock1 = pr_QualifierBlock1();
					_localctx._qualifierBlock1Antlr1.Add(_localctx._pr_QualifierBlock1);
					}
					} 
				}
				State = 200;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_QualifierListContext : ParserRuleContext {
		public Pr_QualifierContext qualifierAntlr1;
		public Pr_QualifierListBlock1Context _pr_QualifierListBlock1;
		public IList<Pr_QualifierListBlock1Context> _qualifierListBlock1Antlr1 = new List<Pr_QualifierListBlock1Context>();
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierListBlock1Context[] pr_QualifierListBlock1() {
			return GetRuleContexts<Pr_QualifierListBlock1Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierListBlock1Context pr_QualifierListBlock1(int i) {
			return GetRuleContext<Pr_QualifierListBlock1Context>(i);
		}
		public Pr_QualifierListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_QualifierList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_QualifierList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_QualifierListContext pr_QualifierList() {
		Pr_QualifierListContext _localctx = new Pr_QualifierListContext(Context, State);
		EnterRule(_localctx, 38, RULE_pr_QualifierList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 201;
			_localctx.qualifierAntlr1 = pr_Qualifier();
			State = 205;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==LR_TComma) {
				{
				{
				State = 202;
				_localctx._pr_QualifierListBlock1 = pr_QualifierListBlock1();
				_localctx._qualifierListBlock1Antlr1.Add(_localctx._pr_QualifierListBlock1);
				}
				}
				State = 207;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_IdentifierContext : ParserRuleContext {
		public IToken tIdentifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TIdentifier() { return GetToken(MetaParser.LR_TIdentifier, 0); }
		public Pr_IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Identifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_IdentifierContext pr_Identifier() {
		Pr_IdentifierContext _localctx = new Pr_IdentifierContext(Context, State);
		EnterRule(_localctx, 40, RULE_pr_Identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 208;
			_localctx.tIdentifierAntlr1 = Match(LR_TIdentifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_EnumLiteralsBlock1Context : ParserRuleContext {
		public IToken tComma;
		public Pr_MetaEnumLiteralContext literalsAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TComma() { return GetToken(MetaParser.LR_TComma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaEnumLiteralContext pr_MetaEnumLiteral() {
			return GetRuleContext<Pr_MetaEnumLiteralContext>(0);
		}
		public Pr_EnumLiteralsBlock1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_EnumLiteralsBlock1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_EnumLiteralsBlock1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_EnumLiteralsBlock1Context pr_EnumLiteralsBlock1() {
		Pr_EnumLiteralsBlock1Context _localctx = new Pr_EnumLiteralsBlock1Context(Context, State);
		EnterRule(_localctx, 42, RULE_pr_EnumLiteralsBlock1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 210;
			_localctx.tComma = Match(LR_TComma);
			State = 211;
			_localctx.literalsAntlr1 = pr_MetaEnumLiteral();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_BaseClassesBlock1Context : ParserRuleContext {
		public IToken tColon;
		public Pr_QualifierListContext baseTypesAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TColon() { return GetToken(MetaParser.LR_TColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierListContext pr_QualifierList() {
			return GetRuleContext<Pr_QualifierListContext>(0);
		}
		public Pr_BaseClassesBlock1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_BaseClassesBlock1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_BaseClassesBlock1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_BaseClassesBlock1Context pr_BaseClassesBlock1() {
		Pr_BaseClassesBlock1Context _localctx = new Pr_BaseClassesBlock1Context(Context, State);
		EnterRule(_localctx, 44, RULE_pr_BaseClassesBlock1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 213;
			_localctx.tColon = Match(LR_TColon);
			State = 214;
			_localctx.baseTypesAntlr1 = pr_QualifierList();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_ParameterListBlock1Context : ParserRuleContext {
		public IToken tComma;
		public Pr_MetaParameterContext parametersAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TComma() { return GetToken(MetaParser.LR_TComma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaParameterContext pr_MetaParameter() {
			return GetRuleContext<Pr_MetaParameterContext>(0);
		}
		public Pr_ParameterListBlock1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_ParameterListBlock1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_ParameterListBlock1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_ParameterListBlock1Context pr_ParameterListBlock1() {
		Pr_ParameterListBlock1Context _localctx = new Pr_ParameterListBlock1Context(Context, State);
		EnterRule(_localctx, 46, RULE_pr_ParameterListBlock1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 216;
			_localctx.tComma = Match(LR_TComma);
			State = 217;
			_localctx.parametersAntlr1 = pr_MetaParameter();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_QualifierBlock1Context : ParserRuleContext {
		public IToken tDot;
		public Pr_IdentifierContext identifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TDot() { return GetToken(MetaParser.LR_TDot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_IdentifierContext pr_Identifier() {
			return GetRuleContext<Pr_IdentifierContext>(0);
		}
		public Pr_QualifierBlock1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_QualifierBlock1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_QualifierBlock1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_QualifierBlock1Context pr_QualifierBlock1() {
		Pr_QualifierBlock1Context _localctx = new Pr_QualifierBlock1Context(Context, State);
		EnterRule(_localctx, 48, RULE_pr_QualifierBlock1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 219;
			_localctx.tDot = Match(LR_TDot);
			State = 220;
			_localctx.identifierAntlr1 = pr_Identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_QualifierListBlock1Context : ParserRuleContext {
		public IToken tComma;
		public Pr_QualifierContext qualifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TComma() { return GetToken(MetaParser.LR_TComma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		public Pr_QualifierListBlock1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_QualifierListBlock1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaParserVisitor<TResult> typedVisitor = visitor as IMetaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_QualifierListBlock1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_QualifierListBlock1Context pr_QualifierListBlock1() {
		Pr_QualifierListBlock1Context _localctx = new Pr_QualifierListBlock1Context(Context, State);
		EnterRule(_localctx, 50, RULE_pr_QualifierListBlock1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 222;
			_localctx.tComma = Match(LR_TComma);
			State = 223;
			_localctx.qualifierAntlr1 = pr_Qualifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 16: return pr_TypeReference_sempred((Pr_TypeReferenceContext)_localctx, predIndex);
		}
		return true;
	}
	private bool pr_TypeReference_sempred(Pr_TypeReferenceContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,34,226,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,1,0,1,0,1,0,1,0,5,0,57,8,0,10,
		0,12,0,60,9,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,2,5,2,70,8,2,10,2,12,2,73,
		9,2,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,3,3,89,8,3,
		1,3,1,3,1,3,3,3,94,8,3,1,3,1,3,3,3,98,8,3,1,4,1,4,3,4,102,8,4,1,4,1,4,
		1,5,1,5,5,5,108,8,5,10,5,12,5,111,9,5,1,6,1,6,1,7,3,7,116,8,7,1,7,1,7,
		1,7,3,7,121,8,7,1,8,1,8,1,9,1,9,5,9,127,8,9,10,9,12,9,130,9,9,1,9,1,9,
		1,10,1,10,3,10,136,8,10,1,10,1,10,1,10,3,10,141,8,10,1,10,1,10,1,11,3,
		11,146,8,11,1,11,1,11,1,11,3,11,151,8,11,1,12,1,12,1,12,1,13,1,13,1,13,
		1,13,3,13,160,8,13,1,13,1,13,1,14,1,14,5,14,166,8,14,10,14,12,14,169,9,
		14,1,15,1,15,1,15,1,16,1,16,1,16,1,16,1,16,1,16,1,16,3,16,181,8,16,3,16,
		183,8,16,1,16,1,16,1,16,5,16,188,8,16,10,16,12,16,191,9,16,1,17,1,17,1,
		18,1,18,5,18,197,8,18,10,18,12,18,200,9,18,1,19,1,19,5,19,204,8,19,10,
		19,12,19,207,9,19,1,20,1,20,1,21,1,21,1,21,1,22,1,22,1,22,1,23,1,23,1,
		23,1,24,1,24,1,24,1,25,1,25,1,25,1,25,0,1,32,26,0,2,4,6,8,10,12,14,16,
		18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,0,0,226,0,52,1,0,0,
		0,2,64,1,0,0,0,4,71,1,0,0,0,6,97,1,0,0,0,8,99,1,0,0,0,10,105,1,0,0,0,12,
		112,1,0,0,0,14,120,1,0,0,0,16,122,1,0,0,0,18,124,1,0,0,0,20,135,1,0,0,
		0,22,150,1,0,0,0,24,152,1,0,0,0,26,155,1,0,0,0,28,163,1,0,0,0,30,170,1,
		0,0,0,32,182,1,0,0,0,34,192,1,0,0,0,36,194,1,0,0,0,38,201,1,0,0,0,40,208,
		1,0,0,0,42,210,1,0,0,0,44,213,1,0,0,0,46,216,1,0,0,0,48,219,1,0,0,0,50,
		222,1,0,0,0,52,53,5,2,0,0,53,54,3,36,18,0,54,58,5,3,0,0,55,57,3,2,1,0,
		56,55,1,0,0,0,57,60,1,0,0,0,58,56,1,0,0,0,58,59,1,0,0,0,59,61,1,0,0,0,
		60,58,1,0,0,0,61,62,3,4,2,0,62,63,5,0,0,1,63,1,1,0,0,0,64,65,5,4,0,0,65,
		66,3,36,18,0,66,67,5,3,0,0,67,3,1,0,0,0,68,70,3,6,3,0,69,68,1,0,0,0,70,
		73,1,0,0,0,71,69,1,0,0,0,71,72,1,0,0,0,72,5,1,0,0,0,73,71,1,0,0,0,74,75,
		5,5,0,0,75,76,3,34,17,0,76,77,5,3,0,0,77,98,1,0,0,0,78,79,5,6,0,0,79,80,
		3,32,16,0,80,81,3,34,17,0,81,82,5,3,0,0,82,98,1,0,0,0,83,84,5,7,0,0,84,
		85,3,34,17,0,85,86,3,8,4,0,86,98,1,0,0,0,87,89,5,10,0,0,88,87,1,0,0,0,
		88,89,1,0,0,0,89,90,1,0,0,0,90,91,5,11,0,0,91,93,3,14,7,0,92,94,3,16,8,
		0,93,92,1,0,0,0,93,94,1,0,0,0,94,95,1,0,0,0,95,96,3,18,9,0,96,98,1,0,0,
		0,97,74,1,0,0,0,97,78,1,0,0,0,97,83,1,0,0,0,97,88,1,0,0,0,98,7,1,0,0,0,
		99,101,5,8,0,0,100,102,3,10,5,0,101,100,1,0,0,0,101,102,1,0,0,0,102,103,
		1,0,0,0,103,104,5,9,0,0,104,9,1,0,0,0,105,109,3,12,6,0,106,108,3,42,21,
		0,107,106,1,0,0,0,108,111,1,0,0,0,109,107,1,0,0,0,109,110,1,0,0,0,110,
		11,1,0,0,0,111,109,1,0,0,0,112,113,3,34,17,0,113,13,1,0,0,0,114,116,5,
		29,0,0,115,114,1,0,0,0,115,116,1,0,0,0,116,117,1,0,0,0,117,118,5,12,0,
		0,118,121,3,40,20,0,119,121,5,29,0,0,120,115,1,0,0,0,120,119,1,0,0,0,121,
		15,1,0,0,0,122,123,3,44,22,0,123,17,1,0,0,0,124,128,5,8,0,0,125,127,3,
		20,10,0,126,125,1,0,0,0,127,130,1,0,0,0,128,126,1,0,0,0,128,129,1,0,0,
		0,129,131,1,0,0,0,130,128,1,0,0,0,131,132,5,9,0,0,132,19,1,0,0,0,133,136,
		5,14,0,0,134,136,5,15,0,0,135,133,1,0,0,0,135,134,1,0,0,0,135,136,1,0,
		0,0,136,137,1,0,0,0,137,138,3,32,16,0,138,140,3,22,11,0,139,141,3,24,12,
		0,140,139,1,0,0,0,140,141,1,0,0,0,141,142,1,0,0,0,142,143,5,3,0,0,143,
		21,1,0,0,0,144,146,5,29,0,0,145,144,1,0,0,0,145,146,1,0,0,0,146,147,1,
		0,0,0,147,148,5,12,0,0,148,151,5,29,0,0,149,151,5,29,0,0,150,145,1,0,0,
		0,150,149,1,0,0,0,151,23,1,0,0,0,152,153,5,16,0,0,153,154,3,36,18,0,154,
		25,1,0,0,0,155,156,3,32,16,0,156,157,3,34,17,0,157,159,5,17,0,0,158,160,
		3,28,14,0,159,158,1,0,0,0,159,160,1,0,0,0,160,161,1,0,0,0,161,162,5,18,
		0,0,162,27,1,0,0,0,163,167,3,30,15,0,164,166,3,46,23,0,165,164,1,0,0,0,
		166,169,1,0,0,0,167,165,1,0,0,0,167,168,1,0,0,0,168,29,1,0,0,0,169,167,
		1,0,0,0,170,171,3,32,16,0,171,172,3,34,17,0,172,31,1,0,0,0,173,174,6,16,
		-1,0,174,183,3,36,18,0,175,181,5,19,0,0,176,181,5,20,0,0,177,181,5,21,
		0,0,178,181,5,22,0,0,179,181,5,23,0,0,180,175,1,0,0,0,180,176,1,0,0,0,
		180,177,1,0,0,0,180,178,1,0,0,0,180,179,1,0,0,0,181,183,1,0,0,0,182,173,
		1,0,0,0,182,180,1,0,0,0,183,189,1,0,0,0,184,185,10,3,0,0,185,186,5,24,
		0,0,186,188,5,25,0,0,187,184,1,0,0,0,188,191,1,0,0,0,189,187,1,0,0,0,189,
		190,1,0,0,0,190,33,1,0,0,0,191,189,1,0,0,0,192,193,3,40,20,0,193,35,1,
		0,0,0,194,198,3,40,20,0,195,197,3,48,24,0,196,195,1,0,0,0,197,200,1,0,
		0,0,198,196,1,0,0,0,198,199,1,0,0,0,199,37,1,0,0,0,200,198,1,0,0,0,201,
		205,3,36,18,0,202,204,3,50,25,0,203,202,1,0,0,0,204,207,1,0,0,0,205,203,
		1,0,0,0,205,206,1,0,0,0,206,39,1,0,0,0,207,205,1,0,0,0,208,209,5,29,0,
		0,209,41,1,0,0,0,210,211,5,1,0,0,211,212,3,12,6,0,212,43,1,0,0,0,213,214,
		5,13,0,0,214,215,3,38,19,0,215,45,1,0,0,0,216,217,5,1,0,0,217,218,3,30,
		15,0,218,47,1,0,0,0,219,220,5,26,0,0,220,221,3,40,20,0,221,49,1,0,0,0,
		222,223,5,1,0,0,223,224,3,36,18,0,224,51,1,0,0,0,21,58,71,88,93,97,101,
		109,115,120,128,135,140,145,150,159,167,180,182,189,198,205
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace MetaDslx.Languages.MetaModel.Compiler
