<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>mgen</string>
    </array>
    <key>name</key>
    <string>MetaGenerator</string>
    <key>scopeName</key>
    <string>source.metadslx.mgen</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#expression</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#letter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#paren-expression</string>
          </dict>
        </array>
      </dict>
      <key>letter</key>
      <dict>
        <key>match</key>
        <string>a|b|c</string>
        <key>name</key>
        <string>keyword.letter</string>
      </dict>
      <key>paren-expression</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.paren.open</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.paren.close</string>
          </dict>
        </dict>
        <key>name</key>
        <string>expression.group</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>