//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MetaCoreParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MetaDslx.Bootstrap.MetaModel.Compiler {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public partial class MetaCoreParser : global::MetaDslx.Languages.MetaCompiler.Antlr.AntlrParser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LR_TComma=1, LR_KNamespace=2, LR_KUsing=3, LR_KMetamodel=4, LR_KEnum=5, 
		LR_TLBrace=6, LR_TRBrace=7, LR_KAbstract=8, LR_KClass=9, LR_TColon=10, 
		LR_KContains=11, LR_KOpposite=12, LR_KBool=13, LR_KInt=14, LR_KString=15, 
		LR_TLBracket=16, LR_TRBracket=17, LR_TDot=18, LR_TInteger=19, LR_TDecimal=20, 
		LR_TIdentifier=21, LR_TString=22, LR_TWhitespace=23, LR_TLineEnd=24, LR_TSingleLineComment=25, 
		LR_TMultiLineComment=26;
	public const int
		RULE_pr_Main = 0, RULE_pr_Using = 1, RULE_pr_Declarations = 2, RULE_pr_MetaDeclaration = 3, 
		RULE_pr_EnumBody = 4, RULE_pr_EnumLiterals = 5, RULE_pr_MetaEnumLiteral = 6, 
		RULE_pr_BaseClasses = 7, RULE_pr_ClassBody = 8, RULE_pr_MetaProperty = 9, 
		RULE_pr_PropertyOpposite = 10, RULE_pr_TypeReference = 11, RULE_pr_Name = 12, 
		RULE_pr_Qualifier = 13, RULE_pr_QualifierList = 14, RULE_pr_Identifier = 15, 
		RULE_pr_EnumLiteralsBlock1 = 16, RULE_pr_BaseClassesBlock1 = 17, RULE_pr_QualifierBlock1 = 18, 
		RULE_pr_QualifierListBlock1 = 19;
	public static readonly string[] ruleNames = {
		"pr_Main", "pr_Using", "pr_Declarations", "pr_MetaDeclaration", "pr_EnumBody", 
		"pr_EnumLiterals", "pr_MetaEnumLiteral", "pr_BaseClasses", "pr_ClassBody", 
		"pr_MetaProperty", "pr_PropertyOpposite", "pr_TypeReference", "pr_Name", 
		"pr_Qualifier", "pr_QualifierList", "pr_Identifier", "pr_EnumLiteralsBlock1", 
		"pr_BaseClassesBlock1", "pr_QualifierBlock1", "pr_QualifierListBlock1"
	};

	private static readonly string[] _LiteralNames = {
		null, "','", "'namespace'", "'using'", "'metamodel'", "'enum'", "'{'", 
		"'}'", "'abstract'", "'class'", "':'", "'contains'", "'opposite'", "'bool'", 
		"'int'", "'string'", "'['", "']'", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LR_TComma", "LR_KNamespace", "LR_KUsing", "LR_KMetamodel", "LR_KEnum", 
		"LR_TLBrace", "LR_TRBrace", "LR_KAbstract", "LR_KClass", "LR_TColon", 
		"LR_KContains", "LR_KOpposite", "LR_KBool", "LR_KInt", "LR_KString", "LR_TLBracket", 
		"LR_TRBracket", "LR_TDot", "LR_TInteger", "LR_TDecimal", "LR_TIdentifier", 
		"LR_TString", "LR_TWhitespace", "LR_TLineEnd", "LR_TSingleLineComment", 
		"LR_TMultiLineComment"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MetaCoreParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static MetaCoreParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MetaCoreParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MetaCoreParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Pr_MainContext : ParserRuleContext {
		public IToken kNamespace;
		public Pr_QualifierContext nameAntlr1;
		public Pr_UsingContext _pr_Using;
		public IList<Pr_UsingContext> _usingAntlr1 = new List<Pr_UsingContext>();
		public Pr_DeclarationsContext declarationsAntlr1;
		public IToken eof;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KNamespace() { return GetToken(MetaCoreParser.LR_KNamespace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_DeclarationsContext pr_Declarations() {
			return GetRuleContext<Pr_DeclarationsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(MetaCoreParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_UsingContext[] pr_Using() {
			return GetRuleContexts<Pr_UsingContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_UsingContext pr_Using(int i) {
			return GetRuleContext<Pr_UsingContext>(i);
		}
		public Pr_MainContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Main; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Main(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MainContext pr_Main() {
		Pr_MainContext _localctx = new Pr_MainContext(Context, State);
		EnterRule(_localctx, 0, RULE_pr_Main);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 40;
			_localctx.kNamespace = Match(LR_KNamespace);
			State = 41;
			_localctx.nameAntlr1 = pr_Qualifier();
			State = 45;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==LR_KUsing) {
				{
				{
				State = 42;
				_localctx._pr_Using = pr_Using();
				_localctx._usingAntlr1.Add(_localctx._pr_Using);
				}
				}
				State = 47;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 48;
			_localctx.declarationsAntlr1 = pr_Declarations();
			State = 49;
			_localctx.eof = Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_UsingContext : ParserRuleContext {
		public IToken kUsing;
		public Pr_QualifierContext namespacesAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KUsing() { return GetToken(MetaCoreParser.LR_KUsing, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		public Pr_UsingContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Using; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Using(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_UsingContext pr_Using() {
		Pr_UsingContext _localctx = new Pr_UsingContext(Context, State);
		EnterRule(_localctx, 2, RULE_pr_Using);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51;
			_localctx.kUsing = Match(LR_KUsing);
			State = 52;
			_localctx.namespacesAntlr1 = pr_Qualifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_DeclarationsContext : ParserRuleContext {
		public Pr_MetaDeclarationContext declarationsAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaDeclarationContext pr_MetaDeclaration() {
			return GetRuleContext<Pr_MetaDeclarationContext>(0);
		}
		public Pr_DeclarationsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Declarations; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Declarations(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_DeclarationsContext pr_Declarations() {
		Pr_DeclarationsContext _localctx = new Pr_DeclarationsContext(Context, State);
		EnterRule(_localctx, 4, RULE_pr_Declarations);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			_localctx.declarationsAntlr1 = pr_MetaDeclaration();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_MetaDeclarationContext : ParserRuleContext {
		public Pr_MetaDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_MetaDeclaration; } }
	 
		public Pr_MetaDeclarationContext() { }
		public virtual void CopyFrom(Pr_MetaDeclarationContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Pr_MetaEnumTypeContext : Pr_MetaDeclarationContext {
		public IToken kEnum;
		public Pr_NameContext nameAntlr1;
		public Pr_EnumBodyContext enumBodyAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KEnum() { return GetToken(MetaCoreParser.LR_KEnum, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_EnumBodyContext pr_EnumBody() {
			return GetRuleContext<Pr_EnumBodyContext>(0);
		}
		public Pr_MetaEnumTypeContext(Pr_MetaDeclarationContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaEnumType(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_MetaModelContext : Pr_MetaDeclarationContext {
		public IToken kMetamodel;
		public Pr_NameContext nameAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KMetamodel() { return GetToken(MetaCoreParser.LR_KMetamodel, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		public Pr_MetaModelContext(Pr_MetaDeclarationContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaModel(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_MetaClassContext : Pr_MetaDeclarationContext {
		public IToken isAbstract;
		public IToken kClass;
		public Pr_NameContext nameAntlr1;
		public Pr_BaseClassesContext baseClassesAntlr1;
		public Pr_ClassBodyContext classBodyAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KClass() { return GetToken(MetaCoreParser.LR_KClass, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_ClassBodyContext pr_ClassBody() {
			return GetRuleContext<Pr_ClassBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KAbstract() { return GetToken(MetaCoreParser.LR_KAbstract, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_BaseClassesContext pr_BaseClasses() {
			return GetRuleContext<Pr_BaseClassesContext>(0);
		}
		public Pr_MetaClassContext(Pr_MetaDeclarationContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaClass(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MetaDeclarationContext pr_MetaDeclaration() {
		Pr_MetaDeclarationContext _localctx = new Pr_MetaDeclarationContext(Context, State);
		EnterRule(_localctx, 6, RULE_pr_MetaDeclaration);
		int _la;
		try {
			State = 72;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LR_KMetamodel:
				_localctx = new Pr_MetaModelContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 56;
				((Pr_MetaModelContext)_localctx).kMetamodel = Match(LR_KMetamodel);
				State = 57;
				((Pr_MetaModelContext)_localctx).nameAntlr1 = pr_Name();
				}
				break;
			case LR_KEnum:
				_localctx = new Pr_MetaEnumTypeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 58;
				((Pr_MetaEnumTypeContext)_localctx).kEnum = Match(LR_KEnum);
				State = 59;
				((Pr_MetaEnumTypeContext)_localctx).nameAntlr1 = pr_Name();
				State = 60;
				((Pr_MetaEnumTypeContext)_localctx).enumBodyAntlr1 = pr_EnumBody();
				}
				break;
			case LR_KAbstract:
			case LR_KClass:
				_localctx = new Pr_MetaClassContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 63;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LR_KAbstract) {
					{
					State = 62;
					((Pr_MetaClassContext)_localctx).isAbstract = Match(LR_KAbstract);
					}
				}

				State = 65;
				((Pr_MetaClassContext)_localctx).kClass = Match(LR_KClass);
				State = 66;
				((Pr_MetaClassContext)_localctx).nameAntlr1 = pr_Name();
				State = 68;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LR_TColon) {
					{
					State = 67;
					((Pr_MetaClassContext)_localctx).baseClassesAntlr1 = pr_BaseClasses();
					}
				}

				State = 70;
				((Pr_MetaClassContext)_localctx).classBodyAntlr1 = pr_ClassBody();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_EnumBodyContext : ParserRuleContext {
		public IToken tLBrace;
		public Pr_EnumLiteralsContext enumLiteralsAntlr1;
		public IToken tRBrace;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TLBrace() { return GetToken(MetaCoreParser.LR_TLBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TRBrace() { return GetToken(MetaCoreParser.LR_TRBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_EnumLiteralsContext pr_EnumLiterals() {
			return GetRuleContext<Pr_EnumLiteralsContext>(0);
		}
		public Pr_EnumBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_EnumBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_EnumBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_EnumBodyContext pr_EnumBody() {
		Pr_EnumBodyContext _localctx = new Pr_EnumBodyContext(Context, State);
		EnterRule(_localctx, 8, RULE_pr_EnumBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			_localctx.tLBrace = Match(LR_TLBrace);
			State = 76;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LR_TIdentifier) {
				{
				State = 75;
				_localctx.enumLiteralsAntlr1 = pr_EnumLiterals();
				}
			}

			State = 78;
			_localctx.tRBrace = Match(LR_TRBrace);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_EnumLiteralsContext : ParserRuleContext {
		public Pr_MetaEnumLiteralContext literalsAntlr1;
		public Pr_EnumLiteralsBlock1Context _pr_EnumLiteralsBlock1;
		public IList<Pr_EnumLiteralsBlock1Context> _enumLiteralsBlock1Antlr1 = new List<Pr_EnumLiteralsBlock1Context>();
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaEnumLiteralContext pr_MetaEnumLiteral() {
			return GetRuleContext<Pr_MetaEnumLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_EnumLiteralsBlock1Context[] pr_EnumLiteralsBlock1() {
			return GetRuleContexts<Pr_EnumLiteralsBlock1Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_EnumLiteralsBlock1Context pr_EnumLiteralsBlock1(int i) {
			return GetRuleContext<Pr_EnumLiteralsBlock1Context>(i);
		}
		public Pr_EnumLiteralsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_EnumLiterals; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_EnumLiterals(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_EnumLiteralsContext pr_EnumLiterals() {
		Pr_EnumLiteralsContext _localctx = new Pr_EnumLiteralsContext(Context, State);
		EnterRule(_localctx, 10, RULE_pr_EnumLiterals);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80;
			_localctx.literalsAntlr1 = pr_MetaEnumLiteral();
			State = 84;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==LR_TComma) {
				{
				{
				State = 81;
				_localctx._pr_EnumLiteralsBlock1 = pr_EnumLiteralsBlock1();
				_localctx._enumLiteralsBlock1Antlr1.Add(_localctx._pr_EnumLiteralsBlock1);
				}
				}
				State = 86;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_MetaEnumLiteralContext : ParserRuleContext {
		public Pr_NameContext nameAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		public Pr_MetaEnumLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_MetaEnumLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaEnumLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MetaEnumLiteralContext pr_MetaEnumLiteral() {
		Pr_MetaEnumLiteralContext _localctx = new Pr_MetaEnumLiteralContext(Context, State);
		EnterRule(_localctx, 12, RULE_pr_MetaEnumLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			_localctx.nameAntlr1 = pr_Name();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_BaseClassesContext : ParserRuleContext {
		public Pr_BaseClassesBlock1Context baseClassesBlock1Antlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_BaseClassesBlock1Context pr_BaseClassesBlock1() {
			return GetRuleContext<Pr_BaseClassesBlock1Context>(0);
		}
		public Pr_BaseClassesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_BaseClasses; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_BaseClasses(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_BaseClassesContext pr_BaseClasses() {
		Pr_BaseClassesContext _localctx = new Pr_BaseClassesContext(Context, State);
		EnterRule(_localctx, 14, RULE_pr_BaseClasses);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 89;
			_localctx.baseClassesBlock1Antlr1 = pr_BaseClassesBlock1();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_ClassBodyContext : ParserRuleContext {
		public IToken tLBrace;
		public Pr_MetaPropertyContext _pr_MetaProperty;
		public IList<Pr_MetaPropertyContext> _propertiesAntlr1 = new List<Pr_MetaPropertyContext>();
		public IToken tRBrace;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TLBrace() { return GetToken(MetaCoreParser.LR_TLBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TRBrace() { return GetToken(MetaCoreParser.LR_TRBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaPropertyContext[] pr_MetaProperty() {
			return GetRuleContexts<Pr_MetaPropertyContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaPropertyContext pr_MetaProperty(int i) {
			return GetRuleContext<Pr_MetaPropertyContext>(i);
		}
		public Pr_ClassBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_ClassBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_ClassBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_ClassBodyContext pr_ClassBody() {
		Pr_ClassBodyContext _localctx = new Pr_ClassBodyContext(Context, State);
		EnterRule(_localctx, 16, RULE_pr_ClassBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91;
			_localctx.tLBrace = Match(LR_TLBrace);
			State = 95;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==LR_KContains) {
				{
				{
				State = 92;
				_localctx._pr_MetaProperty = pr_MetaProperty();
				_localctx._propertiesAntlr1.Add(_localctx._pr_MetaProperty);
				}
				}
				State = 97;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 98;
			_localctx.tRBrace = Match(LR_TRBrace);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_MetaPropertyContext : ParserRuleContext {
		public IToken isContainment;
		public Pr_TypeReferenceContext typeAntlr1;
		public Pr_NameContext nameAntlr1;
		public Pr_PropertyOppositeContext propertyOppositeAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KContains() { return GetToken(MetaCoreParser.LR_KContains, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_TypeReferenceContext pr_TypeReference() {
			return GetRuleContext<Pr_TypeReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_NameContext pr_Name() {
			return GetRuleContext<Pr_NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_PropertyOppositeContext pr_PropertyOpposite() {
			return GetRuleContext<Pr_PropertyOppositeContext>(0);
		}
		public Pr_MetaPropertyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_MetaProperty; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaProperty(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_MetaPropertyContext pr_MetaProperty() {
		Pr_MetaPropertyContext _localctx = new Pr_MetaPropertyContext(Context, State);
		EnterRule(_localctx, 18, RULE_pr_MetaProperty);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			_localctx.isContainment = Match(LR_KContains);
			State = 101;
			_localctx.typeAntlr1 = pr_TypeReference(0);
			State = 102;
			_localctx.nameAntlr1 = pr_Name();
			State = 104;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LR_KOpposite) {
				{
				State = 103;
				_localctx.propertyOppositeAntlr1 = pr_PropertyOpposite();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_PropertyOppositeContext : ParserRuleContext {
		public IToken kOpposite;
		public Pr_QualifierContext OppositeAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KOpposite() { return GetToken(MetaCoreParser.LR_KOpposite, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		public Pr_PropertyOppositeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_PropertyOpposite; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_PropertyOpposite(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_PropertyOppositeContext pr_PropertyOpposite() {
		Pr_PropertyOppositeContext _localctx = new Pr_PropertyOppositeContext(Context, State);
		EnterRule(_localctx, 20, RULE_pr_PropertyOpposite);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			_localctx.kOpposite = Match(LR_KOpposite);
			State = 107;
			_localctx.OppositeAntlr1 = pr_Qualifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_TypeReferenceContext : ParserRuleContext {
		public Pr_TypeReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_TypeReference; } }
	 
		public Pr_TypeReferenceContext() { }
		public virtual void CopyFrom(Pr_TypeReferenceContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Pr_TypeReferenceTokensContext : Pr_TypeReferenceContext {
		public IToken kBool;
		public IToken kInt;
		public IToken kString;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KBool() { return GetToken(MetaCoreParser.LR_KBool, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KInt() { return GetToken(MetaCoreParser.LR_KInt, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_KString() { return GetToken(MetaCoreParser.LR_KString, 0); }
		public Pr_TypeReferenceTokensContext(Pr_TypeReferenceContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_TypeReferenceTokens(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_MetaArrayTypeContext : Pr_TypeReferenceContext {
		public Pr_TypeReferenceContext itemTypeAntlr1;
		public IToken tLBracket;
		public IToken tRBracket;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_TypeReferenceContext pr_TypeReference() {
			return GetRuleContext<Pr_TypeReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TLBracket() { return GetToken(MetaCoreParser.LR_TLBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TRBracket() { return GetToken(MetaCoreParser.LR_TRBracket, 0); }
		public Pr_MetaArrayTypeContext(Pr_TypeReferenceContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_MetaArrayType(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pr_TypeReferenceAlt3Context : Pr_TypeReferenceContext {
		public Pr_QualifierContext qualifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		public Pr_TypeReferenceAlt3Context(Pr_TypeReferenceContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_TypeReferenceAlt3(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_TypeReferenceContext pr_TypeReference() {
		return pr_TypeReference(0);
	}

	private Pr_TypeReferenceContext pr_TypeReference(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		Pr_TypeReferenceContext _localctx = new Pr_TypeReferenceContext(Context, _parentState);
		Pr_TypeReferenceContext _prevctx = _localctx;
		int _startState = 22;
		EnterRecursionRule(_localctx, 22, RULE_pr_TypeReference, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LR_TIdentifier:
				{
				_localctx = new Pr_TypeReferenceAlt3Context(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 110;
				((Pr_TypeReferenceAlt3Context)_localctx).qualifierAntlr1 = pr_Qualifier();
				}
				break;
			case LR_KBool:
			case LR_KInt:
			case LR_KString:
				{
				_localctx = new Pr_TypeReferenceTokensContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 114;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case LR_KBool:
					{
					State = 111;
					((Pr_TypeReferenceTokensContext)_localctx).kBool = Match(LR_KBool);
					}
					break;
				case LR_KInt:
					{
					State = 112;
					((Pr_TypeReferenceTokensContext)_localctx).kInt = Match(LR_KInt);
					}
					break;
				case LR_KString:
					{
					State = 113;
					((Pr_TypeReferenceTokensContext)_localctx).kString = Match(LR_KString);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 123;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new Pr_MetaArrayTypeContext(new Pr_TypeReferenceContext(_parentctx, _parentState));
					((Pr_MetaArrayTypeContext)_localctx).itemTypeAntlr1 = _prevctx;
					PushNewRecursionContext(_localctx, _startState, RULE_pr_TypeReference);
					State = 118;
					if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
					State = 119;
					((Pr_MetaArrayTypeContext)_localctx).tLBracket = Match(LR_TLBracket);
					State = 120;
					((Pr_MetaArrayTypeContext)_localctx).tRBracket = Match(LR_TRBracket);
					}
					} 
				}
				State = 125;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Pr_NameContext : ParserRuleContext {
		public Pr_IdentifierContext identifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public Pr_IdentifierContext pr_Identifier() {
			return GetRuleContext<Pr_IdentifierContext>(0);
		}
		public Pr_NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_NameContext pr_Name() {
		Pr_NameContext _localctx = new Pr_NameContext(Context, State);
		EnterRule(_localctx, 24, RULE_pr_Name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			_localctx.identifierAntlr1 = pr_Identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_QualifierContext : ParserRuleContext {
		public Pr_IdentifierContext identifierAntlr1;
		public Pr_QualifierBlock1Context _pr_QualifierBlock1;
		public IList<Pr_QualifierBlock1Context> _qualifierBlock1Antlr1 = new List<Pr_QualifierBlock1Context>();
		[System.Diagnostics.DebuggerNonUserCode] public Pr_IdentifierContext pr_Identifier() {
			return GetRuleContext<Pr_IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierBlock1Context[] pr_QualifierBlock1() {
			return GetRuleContexts<Pr_QualifierBlock1Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierBlock1Context pr_QualifierBlock1(int i) {
			return GetRuleContext<Pr_QualifierBlock1Context>(i);
		}
		public Pr_QualifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Qualifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Qualifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_QualifierContext pr_Qualifier() {
		Pr_QualifierContext _localctx = new Pr_QualifierContext(Context, State);
		EnterRule(_localctx, 26, RULE_pr_Qualifier);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			_localctx.identifierAntlr1 = pr_Identifier();
			State = 132;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 129;
					_localctx._pr_QualifierBlock1 = pr_QualifierBlock1();
					_localctx._qualifierBlock1Antlr1.Add(_localctx._pr_QualifierBlock1);
					}
					} 
				}
				State = 134;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_QualifierListContext : ParserRuleContext {
		public Pr_QualifierContext qualifierAntlr1;
		public Pr_QualifierListBlock1Context _pr_QualifierListBlock1;
		public IList<Pr_QualifierListBlock1Context> _qualifierListBlock1Antlr1 = new List<Pr_QualifierListBlock1Context>();
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierListBlock1Context[] pr_QualifierListBlock1() {
			return GetRuleContexts<Pr_QualifierListBlock1Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierListBlock1Context pr_QualifierListBlock1(int i) {
			return GetRuleContext<Pr_QualifierListBlock1Context>(i);
		}
		public Pr_QualifierListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_QualifierList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_QualifierList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_QualifierListContext pr_QualifierList() {
		Pr_QualifierListContext _localctx = new Pr_QualifierListContext(Context, State);
		EnterRule(_localctx, 28, RULE_pr_QualifierList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			_localctx.qualifierAntlr1 = pr_Qualifier();
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==LR_TComma) {
				{
				{
				State = 136;
				_localctx._pr_QualifierListBlock1 = pr_QualifierListBlock1();
				_localctx._qualifierListBlock1Antlr1.Add(_localctx._pr_QualifierListBlock1);
				}
				}
				State = 141;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_IdentifierContext : ParserRuleContext {
		public IToken tIdentifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TIdentifier() { return GetToken(MetaCoreParser.LR_TIdentifier, 0); }
		public Pr_IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_Identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_Identifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_IdentifierContext pr_Identifier() {
		Pr_IdentifierContext _localctx = new Pr_IdentifierContext(Context, State);
		EnterRule(_localctx, 30, RULE_pr_Identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142;
			_localctx.tIdentifierAntlr1 = Match(LR_TIdentifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_EnumLiteralsBlock1Context : ParserRuleContext {
		public IToken tComma;
		public Pr_MetaEnumLiteralContext literalsAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TComma() { return GetToken(MetaCoreParser.LR_TComma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_MetaEnumLiteralContext pr_MetaEnumLiteral() {
			return GetRuleContext<Pr_MetaEnumLiteralContext>(0);
		}
		public Pr_EnumLiteralsBlock1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_EnumLiteralsBlock1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_EnumLiteralsBlock1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_EnumLiteralsBlock1Context pr_EnumLiteralsBlock1() {
		Pr_EnumLiteralsBlock1Context _localctx = new Pr_EnumLiteralsBlock1Context(Context, State);
		EnterRule(_localctx, 32, RULE_pr_EnumLiteralsBlock1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 144;
			_localctx.tComma = Match(LR_TComma);
			State = 145;
			_localctx.literalsAntlr1 = pr_MetaEnumLiteral();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_BaseClassesBlock1Context : ParserRuleContext {
		public IToken tColon;
		public Pr_QualifierListContext baseTypesAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TColon() { return GetToken(MetaCoreParser.LR_TColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierListContext pr_QualifierList() {
			return GetRuleContext<Pr_QualifierListContext>(0);
		}
		public Pr_BaseClassesBlock1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_BaseClassesBlock1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_BaseClassesBlock1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_BaseClassesBlock1Context pr_BaseClassesBlock1() {
		Pr_BaseClassesBlock1Context _localctx = new Pr_BaseClassesBlock1Context(Context, State);
		EnterRule(_localctx, 34, RULE_pr_BaseClassesBlock1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147;
			_localctx.tColon = Match(LR_TColon);
			State = 148;
			_localctx.baseTypesAntlr1 = pr_QualifierList();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_QualifierBlock1Context : ParserRuleContext {
		public IToken tDot;
		public Pr_IdentifierContext identifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TDot() { return GetToken(MetaCoreParser.LR_TDot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_IdentifierContext pr_Identifier() {
			return GetRuleContext<Pr_IdentifierContext>(0);
		}
		public Pr_QualifierBlock1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_QualifierBlock1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_QualifierBlock1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_QualifierBlock1Context pr_QualifierBlock1() {
		Pr_QualifierBlock1Context _localctx = new Pr_QualifierBlock1Context(Context, State);
		EnterRule(_localctx, 36, RULE_pr_QualifierBlock1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 150;
			_localctx.tDot = Match(LR_TDot);
			State = 151;
			_localctx.identifierAntlr1 = pr_Identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pr_QualifierListBlock1Context : ParserRuleContext {
		public IToken tComma;
		public Pr_QualifierContext qualifierAntlr1;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LR_TComma() { return GetToken(MetaCoreParser.LR_TComma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pr_QualifierContext pr_Qualifier() {
			return GetRuleContext<Pr_QualifierContext>(0);
		}
		public Pr_QualifierListBlock1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pr_QualifierListBlock1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMetaCoreParserVisitor<TResult> typedVisitor = visitor as IMetaCoreParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPr_QualifierListBlock1(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pr_QualifierListBlock1Context pr_QualifierListBlock1() {
		Pr_QualifierListBlock1Context _localctx = new Pr_QualifierListBlock1Context(Context, State);
		EnterRule(_localctx, 38, RULE_pr_QualifierListBlock1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153;
			_localctx.tComma = Match(LR_TComma);
			State = 154;
			_localctx.qualifierAntlr1 = pr_Qualifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 11: return pr_TypeReference_sempred((Pr_TypeReferenceContext)_localctx, predIndex);
		}
		return true;
	}
	private bool pr_TypeReference_sempred(Pr_TypeReferenceContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,26,157,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,1,0,1,0,1,0,5,0,44,8,
		0,10,0,12,0,47,9,0,1,0,1,0,1,0,1,1,1,1,1,1,1,2,1,2,1,3,1,3,1,3,1,3,1,3,
		1,3,1,3,3,3,64,8,3,1,3,1,3,1,3,3,3,69,8,3,1,3,1,3,3,3,73,8,3,1,4,1,4,3,
		4,77,8,4,1,4,1,4,1,5,1,5,5,5,83,8,5,10,5,12,5,86,9,5,1,6,1,6,1,7,1,7,1,
		8,1,8,5,8,94,8,8,10,8,12,8,97,9,8,1,8,1,8,1,9,1,9,1,9,1,9,3,9,105,8,9,
		1,10,1,10,1,10,1,11,1,11,1,11,1,11,1,11,3,11,115,8,11,3,11,117,8,11,1,
		11,1,11,1,11,5,11,122,8,11,10,11,12,11,125,9,11,1,12,1,12,1,13,1,13,5,
		13,131,8,13,10,13,12,13,134,9,13,1,14,1,14,5,14,138,8,14,10,14,12,14,141,
		9,14,1,15,1,15,1,16,1,16,1,16,1,17,1,17,1,17,1,18,1,18,1,18,1,19,1,19,
		1,19,1,19,0,1,22,20,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,
		38,0,0,151,0,40,1,0,0,0,2,51,1,0,0,0,4,54,1,0,0,0,6,72,1,0,0,0,8,74,1,
		0,0,0,10,80,1,0,0,0,12,87,1,0,0,0,14,89,1,0,0,0,16,91,1,0,0,0,18,100,1,
		0,0,0,20,106,1,0,0,0,22,116,1,0,0,0,24,126,1,0,0,0,26,128,1,0,0,0,28,135,
		1,0,0,0,30,142,1,0,0,0,32,144,1,0,0,0,34,147,1,0,0,0,36,150,1,0,0,0,38,
		153,1,0,0,0,40,41,5,2,0,0,41,45,3,26,13,0,42,44,3,2,1,0,43,42,1,0,0,0,
		44,47,1,0,0,0,45,43,1,0,0,0,45,46,1,0,0,0,46,48,1,0,0,0,47,45,1,0,0,0,
		48,49,3,4,2,0,49,50,5,0,0,1,50,1,1,0,0,0,51,52,5,3,0,0,52,53,3,26,13,0,
		53,3,1,0,0,0,54,55,3,6,3,0,55,5,1,0,0,0,56,57,5,4,0,0,57,73,3,24,12,0,
		58,59,5,5,0,0,59,60,3,24,12,0,60,61,3,8,4,0,61,73,1,0,0,0,62,64,5,8,0,
		0,63,62,1,0,0,0,63,64,1,0,0,0,64,65,1,0,0,0,65,66,5,9,0,0,66,68,3,24,12,
		0,67,69,3,14,7,0,68,67,1,0,0,0,68,69,1,0,0,0,69,70,1,0,0,0,70,71,3,16,
		8,0,71,73,1,0,0,0,72,56,1,0,0,0,72,58,1,0,0,0,72,63,1,0,0,0,73,7,1,0,0,
		0,74,76,5,6,0,0,75,77,3,10,5,0,76,75,1,0,0,0,76,77,1,0,0,0,77,78,1,0,0,
		0,78,79,5,7,0,0,79,9,1,0,0,0,80,84,3,12,6,0,81,83,3,32,16,0,82,81,1,0,
		0,0,83,86,1,0,0,0,84,82,1,0,0,0,84,85,1,0,0,0,85,11,1,0,0,0,86,84,1,0,
		0,0,87,88,3,24,12,0,88,13,1,0,0,0,89,90,3,34,17,0,90,15,1,0,0,0,91,95,
		5,6,0,0,92,94,3,18,9,0,93,92,1,0,0,0,94,97,1,0,0,0,95,93,1,0,0,0,95,96,
		1,0,0,0,96,98,1,0,0,0,97,95,1,0,0,0,98,99,5,7,0,0,99,17,1,0,0,0,100,101,
		5,11,0,0,101,102,3,22,11,0,102,104,3,24,12,0,103,105,3,20,10,0,104,103,
		1,0,0,0,104,105,1,0,0,0,105,19,1,0,0,0,106,107,5,12,0,0,107,108,3,26,13,
		0,108,21,1,0,0,0,109,110,6,11,-1,0,110,117,3,26,13,0,111,115,5,13,0,0,
		112,115,5,14,0,0,113,115,5,15,0,0,114,111,1,0,0,0,114,112,1,0,0,0,114,
		113,1,0,0,0,115,117,1,0,0,0,116,109,1,0,0,0,116,114,1,0,0,0,117,123,1,
		0,0,0,118,119,10,3,0,0,119,120,5,16,0,0,120,122,5,17,0,0,121,118,1,0,0,
		0,122,125,1,0,0,0,123,121,1,0,0,0,123,124,1,0,0,0,124,23,1,0,0,0,125,123,
		1,0,0,0,126,127,3,30,15,0,127,25,1,0,0,0,128,132,3,30,15,0,129,131,3,36,
		18,0,130,129,1,0,0,0,131,134,1,0,0,0,132,130,1,0,0,0,132,133,1,0,0,0,133,
		27,1,0,0,0,134,132,1,0,0,0,135,139,3,26,13,0,136,138,3,38,19,0,137,136,
		1,0,0,0,138,141,1,0,0,0,139,137,1,0,0,0,139,140,1,0,0,0,140,29,1,0,0,0,
		141,139,1,0,0,0,142,143,5,21,0,0,143,31,1,0,0,0,144,145,5,1,0,0,145,146,
		3,12,6,0,146,33,1,0,0,0,147,148,5,10,0,0,148,149,3,28,14,0,149,35,1,0,
		0,0,150,151,5,18,0,0,151,152,3,30,15,0,152,37,1,0,0,0,153,154,5,1,0,0,
		154,155,3,26,13,0,155,39,1,0,0,0,13,45,63,68,72,76,84,95,104,114,116,123,
		132,139
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace MetaDslx.Bootstrap.MetaModel.Compiler
